<?php
/**
 * include/config.dist.php is base config file.
 * Please copy include/config.dist.php to include/config.php and make
 * any needed changes. Do not edit this file.
 */

# this has to be set to string of your choice. This is the password that will be
# required. To generate a simple MD5 password hash, call
# crypt('passwordOfChoice', '$1$saltOfChoice$') and use the value returned here.
$conf['expectedPasswordHash'] = null;

# require a password to be provided when making proxy requests, to not allow just
# anyone to use this service.
$conf['requirePassword'] = true;
